import { GitHubUser } from "./githubUser";

export class GitHubRepo {
  allow_forking?: boolean | undefined;
  archive_url?: string;
  archived?: boolean | undefined;
  assignees_url?: string;
  blobs_url?: string;
  branches_url?: string;
  clone_url?: string;
  collaborators_url?: string;
  comments_url?: string;
  commits_url?: string;
  compare_url?: string;
  contents_url?: string;
  contributors_url?: string;
  created_at?: string;
  default_branch?: string;
  deployments_url?: string;
  description?: string | null;
  disabled?: boolean | undefined;
  downloads_url?: string;
  events_url?: string;
  fork?: boolean | undefined;
  forks?: number;
  forks_count?: number;
  forks_url?: string;
  full_name?: string;
  git_commits_url?: string;
  git_refs_url?: string;
  git_tags_url?: string;
  git_url?: string;
  has_discussions?: boolean | undefined;
  has_downloads?: boolean | undefined;
  has_issues?: boolean | undefined;
  has_pages?: boolean | undefined;
  has_projects?: boolean | undefined;
  has_wiki?: boolean | undefined;
  homepage?: string | null;
  hooks_url?: string;
  html_url?: string;
  id?: number;
  is_template?: boolean | undefined;
  issue_comment_url?: string;
  issue_events_url?: string;
  issues_url?: string;
  keys_url?: string;
  labels_url?: string;
  language?: string;
  languages_url?: string;
  license?: any | null;
  merges_url?: string;
  milestones_url?: string;
  mirror_url?: string | null;
  name?: string;
  node_id?: string;
  notifications_url?: string;
  open_issues?: number;
  open_issues_count?: number;
  owner?: GitHubUser;
  private?: boolean | undefined;
  pulls_url?: string;
  pushed_at?: string;
  releases_url?: string;
  size?: number;
  ssh_url?: string;
  stargazers_count?: number;
  stargazers_url?: string;
  statuses_url?: string;
  subscribers_url?: string;
  subscription_url?: string;
  svn_url?: string;
  tags_url?: string;
  teams_url?: string;
  topics?: string[];
  trees_url?: string;
  updated_at?: string;
  url?: string;
  visibility?: string;
  watchers?: number;
  watchers_count?: number;
  web_commit_signoff_required?: boolean | undefined;

  constructor(data: Partial<GitHubRepo>) {
    this.allow_forking = data.allow_forking ?? false;
    this.archive_url = data.archive_url ?? '';
    this.archived = data.archived ?? false;
    this.assignees_url = data.assignees_url ?? '';
    this.blobs_url = data.blobs_url ?? '';
    this.branches_url = data.branches_url ?? '';
    this.clone_url = data.clone_url ?? '';
    this.collaborators_url = data.collaborators_url ?? '';
    this.comments_url = data.comments_url ?? '';
    this.commits_url = data.commits_url ?? '';
    this.compare_url = data.compare_url ?? '';
    this.contents_url = data.contents_url ?? '';
    this.contributors_url = data.contributors_url ?? '';
    this.created_at = data.created_at ?? '';
    this.default_branch = data.default_branch ?? '';
    this.deployments_url = data.deployments_url ?? '';
    this.description = data.description ?? null;
    this.disabled = data.disabled ?? false;
    this.downloads_url = data.downloads_url ?? '';
    this.events_url = data.events_url ?? '';
    this.fork = data.fork ?? false;
    this.forks = data.forks ?? 0;
    this.forks_count = data.forks_count ?? 0;
    this.forks_url = data.forks_url ?? '';
    this.full_name = data.full_name ?? '';
    this.git_commits_url = data.git_commits_url ?? '';
    this.git_refs_url = data.git_refs_url ?? '';
    this.git_tags_url = data.git_tags_url ?? '';
    this.git_url = data.git_url ?? '';
    this.has_discussions = data.has_discussions ?? false;
    this.has_downloads = data.has_downloads ?? false;
    this.has_issues = data.has_issues ?? false;
    this.has_pages = data.has_pages ?? false;
    this.has_projects = data.has_projects ?? false;
    this.has_wiki = data.has_wiki ?? false;
    this.homepage = data.homepage ?? null;
    this.hooks_url = data.hooks_url ?? '';
    this.html_url = data.html_url ?? '';
    this.id = data.id ?? 0;
    this.is_template = data.is_template ?? false;
    this.issue_comment_url = data.issue_comment_url ?? '';
    this.issue_events_url = data.issue_events_url ?? '';
    this.issues_url = data.issues_url ?? '';
    this.keys_url = data.keys_url ?? '';
    this.labels_url = data.labels_url ?? '';
    this.language = data.language ?? '';
    this.languages_url = data.languages_url ?? '';
    this.license = data.license ?? null;
    this.merges_url = data.merges_url ?? '';
    this.milestones_url = data.milestones_url ?? '';
    this.mirror_url = data.mirror_url ?? null;
    this.name = data.name ?? '';
    this.node_id = data.node_id ?? '';
    this.notifications_url = data.notifications_url ?? '';
    this.open_issues = data.open_issues ?? 0;
    this.open_issues_count = data.open_issues_count ?? 0;
    this.owner = data.owner;
    this.private = data.private ?? false;
    this.pulls_url = data.pulls_url ?? '';
    this.pushed_at = data.pushed_at ?? '';
    this.releases_url = data.releases_url ?? '';
    this.size = data.size ?? 0;
    this.ssh_url = data.ssh_url ?? '';
    this.stargazers_count = data.stargazers_count ?? 0;
    this.stargazers_url = data.stargazers_url ?? '';
    this.statuses_url = data.statuses_url ?? '';
    this.subscribers_url = data.subscribers_url ?? '';
    this.subscription_url = data.subscription_url ?? '';
    this.svn_url = data.svn_url ?? '';
    this.tags_url = data.tags_url ?? '';
    this.teams_url = data.teams_url ?? '';
    this.topics = data.topics ?? [];
    this.trees_url = data.trees_url ?? '';
    this.updated_at = data.updated_at ?? '';
    this.url = data.url ?? '';
    this.visibility = data.visibility ?? '';
    this.watchers = data.watchers ?? 0;
    this.watchers_count = data.watchers_count ?? 0;
    this.web_commit_signoff_required = data.web_commit_signoff_required ?? false;
  }
}
